from .RequestConfigurationMenu import RequestConfigurationMenu
from .RequestsMenu import RequestsMenu
from .MakeRequestMenu import MakeRequestMenu
from .ResourceConfigurationMenu import ResourceConfigurationMenu
from .ResourcesMenu import ResourcesMenu